# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [17.x]
        include:
          - os: ubuntu-latest
            node-version: 17.x
            reportCoverage: true
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm version
    - run: npm install
    - run: npm test
    - run: npm run e2e
      env:
        E2E_CLIENT_ID: ${{ secrets.E2E_CLIENT_ID }}
        E2E_CLIENT_SECRET: ${{ secrets.E2E_CLIENT_SECRET }}
        E2E_TA_EMAIL: ${{ secrets.E2E_TA_EMAIL }}
        E2E_IMS_ORG_ID: ${{ secrets.E2E_IMS_ORG_ID }}
        E2E_PRIVATE_KEY_B64: ${{ secrets.E2E_PRIVATE_KEY_B64 }}
    - run: npm run semantic-release-dry-run
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      if: matrix.reportCoverage
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
