name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - name: End to End Test
        run: npm run e2e
        env:
          E2E_CLIENT_ID: ${{ secrets.E2E_CLIENT_ID }}
          E2E_CLIENT_SECRET: ${{ secrets.E2E_CLIENT_SECRET }}
          E2E_TA_EMAIL: ${{ secrets.E2E_TA_EMAIL }}
          E2E_IMS_ORG_ID: ${{ secrets.E2E_IMS_ORG_ID }}
          E2E_PRIVATE_KEY_B64: ${{ secrets.E2E_PRIVATE_KEY_B64 }}
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          HUSKY_DEBUG: '1'
          HUSKY: '0'
        run: npm run semantic-release
